import {
  IconBrandGmail,
  IconBrandInstagram,
  IconBrandYoutube,
  IconBrandWhatsapp,
  IconBrandSpotify,
  IconBrandSkype,
  IconBrandTwitter,
  IconBrandFacebook,
  IconBrandLinkedin,
} from "@tabler/icons-react";

export const mockdata = [
  { title: "Facebook", icon: IconBrandFacebook, color: "blue" },
  { title: "Gmail", icon: IconBrandGmail, color: "red" },
  {
    title: "Insatagram",
    icon: IconBrandInstagram,
    color: "pink",
  },
  { title: "Youtube", icon: IconBrandYoutube, color: "red" },
  { title: "Whatsapp", icon: IconBrandWhatsapp, color: "green" },
  { title: "Spotify", icon: IconBrandSpotify, color: "green" },
  { title: "Linkden", icon: IconBrandLinkedin, color: "blue" },
  { title: "Twitter", icon: IconBrandTwitter, color: "blue" },
  { title: "Skype", icon: IconBrandSkype, color: "blue" },
];

export const appList = [
  "Grammatica",
  "Audrey Software",
  "Sublime Analytics",
  "Develop Digital",
  "abletika",
  "birenbaum",
  "cilfur",
  "electica",
  "funds-on",
  "goto",
  "holiphone",
  "IBMformobile",
  "jojo apps",
  "kilomentr",
  "lo-lo",
  "mindspace",
  "no mind",
  "oparin",
  "party-house",
  "quadro",
  "raw meat",
  "save it",
  "tech to all",
  "up-app",
  "vendor app",
  "wow app",
  "x-app",
  "y-app",
  "z-app",
];
